airflow:
  url: "http://localhost:8080/health"
  interval: 5s
  field: "metadatabase.status"
  value: "healthy"

airflow-scheduler:
  url: "http://localhost:8080/health"
  interval: 10s
  field: "scheduler.status"
  value: "healthy"
