airflow:
  url: "http://srvanalytic01.poupex.com.br:8080/health"
  interval: 10s
  field: "metadatabase.status"
  value: "healthy"

airflow-scheduler:
  url: "http://srvanalytic01.poupex.com.br:8080/health"
  interval: 10s
  field: "scheduler.status"
  value: "healthy"
